MD013:
    line_length: 120

# Allow certain punctuation at the end of headings
MD026:
    # These are the characters that count as punctuation. Note that '?' and '!' are
    # not mentioned, so they do _not_ count as punctuation, so they are allowed.
    punctuation: ".,;:"

# Allow inline HTML (mostly to allow <a> tags on headings).
MD033: false

# Don't complain about the file not starting with a heading, because we put a TOC link at the top of each page.
MD041: false
